# Generated by Django 2.2.7 on 2019-11-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20191130_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingrecord',
            name='finish_flag',
            field=models.BooleanField(default=False),
        ),
    ]
