# Generated by Django 2.2.7 on 2019-11-30 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_readingrecord_finish_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingrecord',
            old_name='finish_reading_date',
            new_name='finish_date',
        ),
        migrations.RenameField(
            model_name='readingrecord',
            old_name='start_reading_date',
            new_name='start_date',
        ),
    ]
