# Generated by Django 2.2.7 on 2019-12-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20191130_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingrecord',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='readingrecord',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
