# Generated by Django 2.2.7 on 2019-12-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20191201_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingrecord',
            name='read_page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingrecord',
            name='read_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
