# Generated by Django 2.2.7 on 2019-12-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20191201_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingrecord',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
